###

# Фильмы
## Добавить новый фильм
POST http://localhost:4200/movies/create HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFib2JhMUBnbWFpbC5jb20iLCJpZCI6IjYzYzU3OTQ3MTEyNWZkZjNiNTBhYmRmOSIsImlhdCI6MTY3Mzg4NjI1NSwiZXhwIjoxNjc0MDU5MDU1fQ.MYtgl8HhwGuy-aTrD_sUJYTSkQCEunzNcPfPg2bwNVY

{
  "movieName": "Shrekotar",
  "movieDescription": "description, description, description, description",
  "publishDate": "2022-10-21T22:55:33.903Z",
  "genre": "comedy",
  "releaseYear": 1990,
  "previewVideoPath": "https://www.what-to-watch.ru/hunger_games_preview",
  "videoPath": "https://www.what-to-watch.ru/hunger_games",
  "actors": [
    "actor1",
    "actor2",
    "actor3"
  ],
  "director": "Director Directorovich",
  "movieDuration": 120,
  "posterPath": "avatar.jpg",
  "backgroundPath": "avatar.jpg",
  "backgroundColor": "green",
  "isPromo": true
}

###

## Редактирование карточки фильма
PATCH http://localhost:4200/movies/63c57b7e1125fdf3b50abe1c HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFib2JhMUBnbWFpbC5jb20iLCJpZCI6IjYzYzU3OTQ3MTEyNWZkZjNiNTBhYmRmOSIsImlhdCI6MTY3Mzg4NjI1NSwiZXhwIjoxNjc0MDU5MDU1fQ.MYtgl8HhwGuy-aTrD_sUJYTSkQCEunzNcPfPg2bwNVY

{
  "movieName": "Shrekatar",
  "movieDescription": "description, description, description, description",
  "publishDate": "2022-10-21T22:55:33.903Z",
  "genre": "comedy",
  "releaseYear": 2010,
  "previewVideoPath": "https://www.what-to-watch.ru/hunger_games_preview",
  "videoPath": "https://www.what-to-watch.ru/hunger_games",
  "actors": [
    "actor1",
    "actor2",
    "actor3"
  ],
  "director": "Director Directorovich",
  "movieDuration": 120,
  "posterPath": "avatar.jpg",
  "backgroundPath": "avatar.jpg",
  "backgroundColor": "green",
  "isPromo": true
}

###

## Удаление карточки фильма
DELETE http://localhost:4200/movies/63c3f1a7e10f75724c49e8d3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFib2JhMUBnbWFpbC5jb20iLCJpZCI6IjYzYzU3OTQ3MTEyNWZkZjNiNTBhYmRmOSIsImlhdCI6MTY3Mzg4NjI1NSwiZXhwIjoxNjc0MDU5MDU1fQ.MYtgl8HhwGuy-aTrD_sUJYTSkQCEunzNcPfPg2bwNVY

###

## Получить список фильмов
GET http://localhost:4200/movies?limit=1 HTTP/1.1
Accept: application/json

###

## Получение списка фильмов определенного жанра
GET http://localhost:4200/movies?genre=drama HTTP/1.1
Accept: application/json

###

## Получение информации по фильму
GET http://localhost:4200/movies/63c3f1a7e10f75724c49e8d3 HTTP/1.1
Accept: application/json

###

## Получение промо-фильма
GET http://localhost:4200/movies/promo HTTP/1.1
Accept: application/json

###

## Получить список фильмов «К просмотру»
GET http://localhost:4200/users/to_watch HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFib2JhMUBnbWFpbC5jb20iLCJpZCI6IjYzYzU3OTQ3MTEyNWZkZjNiNTBhYmRmOSIsImlhdCI6MTY3Mzg4NjI1NSwiZXhwIjoxNjc0MDU5MDU1fQ.MYtgl8HhwGuy-aTrD_sUJYTSkQCEunzNcPfPg2bwNVY

###

## Добавить фильм в список «К просмотру»
POST http://localhost:4200/users/to_watch HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFib2JhMUBnbWFpbC5jb20iLCJpZCI6IjYzYzU3OTQ3MTEyNWZkZjNiNTBhYmRmOSIsImlhdCI6MTY3Mzg4NjI1NSwiZXhwIjoxNjc0MDU5MDU1fQ.MYtgl8HhwGuy-aTrD_sUJYTSkQCEunzNcPfPg2bwNVY

{
"movieId": "63c3f1a7e10f75724c49e8d3"
}

###

## Удалить фильм из списка «К просмотру»
DELETE http://localhost:4200/users/to_watch HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFib2JhMUBnbWFpbC5jb20iLCJpZCI6IjYzYzU3OTQ3MTEyNWZkZjNiNTBhYmRmOSIsImlhdCI6MTY3Mzg4NjI1NSwiZXhwIjoxNjc0MDU5MDU1fQ.MYtgl8HhwGuy-aTrD_sUJYTSkQCEunzNcPfPg2bwNVY

{
  "movieId": "63c3f1a7e10f75724c49e8d3"
}

###

# Комментарии
## Получить список комментариев для определённого фильма
GET http://localhost:4200/movies/63c3f1a7e10f75724c49e8d3/comments HTTP/1.1
Accept: application/json

###

## Добавить новый комментарий к определённому фильму
POST http://localhost:4200/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFib2JhMUBnbWFpbC5jb20iLCJpZCI6IjYzYzU3OTQ3MTEyNWZkZjNiNTBhYmRmOSIsImlhdCI6MTY3Mzg4NjI1NSwiZXhwIjoxNjc0MDU5MDU1fQ.MYtgl8HhwGuy-aTrD_sUJYTSkQCEunzNcPfPg2bwNVY

{
  "text": "shrek coolooss",
  "rating": 5,
  "movieId": "63c3f1a7e10f75724c49e8d3"
}

###

# Пользователи
## Создание нового пользователя
POST http://localhost:4200/users/register HTTP/1.1
Content-Type: multipart/form-data; boundary=HereGoes

--HereGoes
Content-Disposition: form-data; name="email"
Content-Type: text/plain

aboba1@gmail.com
--HereGoes
Content-Disposition: form-data; name="name"
Content-Type: text/plain

capybara
--HereGoes
Content-Disposition: form-data; name="password"
Content-Type: text/plain

1234567890
--HereGoes
Content-Disposition: form-data; name="avatar"; filename="avatar.png"
Content-Type: image/png

< /Users/lvov/Desktop/photo_2022-09-15_18-47-28 (1).jpeg
--HereGoes--

###

## Отправка аватарки пользователя
POST http://localhost:4200/users/63c579471125fdf3b50abdf9/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar.png"
Content-Type: image/png

< /Users/lvov/Desktop/photo_2022-10-30_12-58-57.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Вход в закрытую часть приложения
POST http://localhost:4200/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "aboba1@gmail.com",
  "password": "1234567890"
}

###

## Проверка токена пользователя
GET http://localhost:4200/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFib2JhMUBnbWFpbC5jb20iLCJpZCI6IjYzYzU3OTQ3MTEyNWZkZjNiNTBhYmRmOSIsImlhdCI6MTY3Mzg4NjI1NSwiZXhwIjoxNjc0MDU5MDU1fQ.MYtgl8HhwGuy-aTrD_sUJYTSkQCEunzNcPfPg2bwNVY
